### PR TITLE
Add brewing stand block and inventory support, minor fixes

### LINKED ISSUE #40: Complete brewing stand support
See https://github.com/DenizenScript/Denizen/issues/2046

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/BrewingStand.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/BrewerInventory.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/BrewingStandFuelEvent.html

Some of these would be for convenience and others new tag/mec pairs. The lead dev is having a hard time comprehending my request, I hope we have better inference skills ;)

### PR DESCRIPTION
**Pull request by MusicScore**
Fixes #40

### CODE REVIEW

File: plugin/src/main/java/com/denizenscript/denizen/objects/InventoryTag.java [hunk 1]
```diff
@@ -668,6 +672,44 @@ public ItemTag getSmelting() {
...
+            ((FurnaceInventory) inventory).setFuel(item);
+        }
+        else if (inventory instanceof BrewerInventory) {
+            ((BrewerInventory) inventory).setFuel(item);
+        }
+    }
+
+    public void setSmelting(ItemStack item) {
+        if (inventory instanceof FurnaceInventory) {
+            ((FurnaceInventory) inventory).setFuel(item);
```
Comment (mergu) [inline plugin/src/main/java/com/denizenscript/denizen/objects/InventoryTag.java]: Is this correct? Seems to be duplicate of the method above

**Comment by mergu** [comment]
My only other suggestion for this would be a tag/mec pair for getting and setting the result slots too. Spigot doesn't provide that but you can reference them as inventory slots and set them. They should accept/output a list of length 3

**Comment by ghost** [comment]
Fix implemented, new tag/mec pair added (`<InventoryTag.bottles>` and `InventoryTag.bottles`).

Tested to work on Paper 1.14.4.

EDIT: Changed "bottles" to "brewing_results".

**Review by mergu — APPROVED** [review]

**Review by Xenmai — APPROVED** [review]
